name: Run Job Skill Analyzer
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Check CSV file exists
      run: |
        if [ ! -f jobs.csv ]; then
          echo " jobs.csv not found!" && exit 1
        fi

    - name: Run analysis script
      run: python job_analysis.py
      env:
        PYTHONIOENCODING: utf-8
        TARGET_SKILL: JavaScript

    - name: Upload job results
      uses: actions/upload-artifact@v4
      with:
        name: job-analysis-results
        path: job_results.txt

